package dev.dhyto.fpl.shared.core.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF8A3D9E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFCD6FF)
val md_theme_light_onPrimaryContainer = Color(0xFF340042)
val md_theme_light_secondary = Color(0xFF7A4998)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF5D9FF)
val md_theme_light_onSecondaryContainer = Color(0xFF30004B)
val md_theme_light_tertiary = Color(0xFF7F4894)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF8D8FF)
val md_theme_light_onTertiaryContainer = Color(0xFF320046)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FDFF)
val md_theme_light_onBackground = Color(0xFF001F25)
val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F25)
val md_theme_light_surfaceVariant = Color(0xFFECDFE9)
val md_theme_light_onSurfaceVariant = Color(0xFF4C444C)
val md_theme_light_outline = Color(0xFF7E747D)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFFF3AEFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF8A3D9E)
val md_theme_light_outlineVariant = Color(0xFFCFC3CD)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFF3AEFF)
val md_theme_dark_onPrimary = Color(0xFF55006B)
val md_theme_dark_primaryContainer = Color(0xFF6F2284)
val md_theme_dark_onPrimaryContainer = Color(0xFFFCD6FF)
val md_theme_dark_secondary = Color(0xFFE5B4FF)
val md_theme_dark_onSecondary = Color(0xFF481866)
val md_theme_dark_secondaryContainer = Color(0xFF61317E)
val md_theme_dark_onSecondaryContainer = Color(0xFFF5D9FF)
val md_theme_dark_tertiary = Color(0xFFECB1FF)
val md_theme_dark_onTertiary = Color(0xFF4C1662)
val md_theme_dark_tertiaryContainer = Color(0xFF65307A)
val md_theme_dark_onTertiaryContainer = Color(0xFFF8D8FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF4C444C)
val md_theme_dark_onSurfaceVariant = Color(0xFFCFC3CD)
val md_theme_dark_outline = Color(0xFF988E97)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF8A3D9E)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFF3AEFF)
val md_theme_dark_outlineVariant = Color(0xFF4C444C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF681A7D)
val CustomColor1 = Color(0xFF8A32A0)
val light_CustomColor1 = Color(0xFF8F37A5)
val light_onCustomColor1 = Color(0xFFFFFFFF)
val light_CustomColor1Container = Color(0xFFFDD6FF)
val light_onCustomColor1Container = Color(0xFF340042)
val dark_CustomColor1 = Color(0xFFF4AEFF)
val dark_onCustomColor1 = Color(0xFF55006A)
val dark_CustomColor1Container = Color(0xFF74198B)
val dark_onCustomColor1Container = Color(0xFFFDD6FF)
